# Site settings
title: Emil Møller Rasmussen
description: Min side
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emil Møller Rasmussen
user_description: I am a tech-savvy analyst. I have built data infrastructure, created machine learning models, implemented systems and done end-to-end analyses. I am passionate about applying my technical know-how to real-life problems. 
user_title: (geo) Data Scientist, Data Engineer, Analyst, Reader
email: emilmrasmussen@pm.me
# twitter_username: lorem_ipsum
instagram_username: 
facebook_username: 
linkedin_username: emr-dk
github_username:  emr-dk
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

