baseURL = "https://min-site-4qma6.ondigitalocean.app"
languageCode = "da-dk"
title = "Min side"
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "Emil Møller Rasmussen ©"


[params]
  name = "Emil Rasmussen"
  description = "Data. Analysis. Good times"
  initials = "EMR"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "github.com/gisemil"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "linkedin.com/gisemil"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Ord"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Projekter"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Bibliotek"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Om"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'blog_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
